env:
  browser: true
  node: true
  commonjs: true
  es6: true
  amd: true
  jquery: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
rules:
  indent:
    - error
    - 2
  no-unused-vars:
    - off
  semi:
    - error
    - always
