env:
  browser: true
  node: true
  commonjs: true
  es6: true
extends: 'eslint:recommended'
parser: 'babel-eslint'
parserOptions:
  ecmaFeatures:
    experimentalObjectRestSpread: true
    experimentalDecorators: true
    jsx: true
    modules: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - error
    - 2
  no-unused-vars:
    - off
  semi:
    - error
    - always
  no-console:
    - off
  flowtype/define-flow-type: 1
  flowtype/use-flow-type: 1
  flowtype/boolean-style: [2, boolean]
  flowtype/semi: [2, always]
  flowtype/space-after-type-colon: [2, always]
  flowtype/space-before-type-colon: [2, never]
  flowtype/space-before-generic-bracket: [2, never]
  flowtype/union-intersection-spacing: [2, always]
  flowtype/no-primitive-constructor-types: 2
  flowtype/no-weak-types: [2, { "any": false }]
  flowtype/object-type-delimiter: [2, comma]
  flowtype/require-valid-file-annotation: 2
  flowtype/require-parameter-type: 1
  flowtype/require-return-type: [1, always, annotateUndefined: never]
  flowtype/valid-syntax: 1
settings:
  flowtype:
    onlyFilesWithFlowAnnotation: true
